name: langchain_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  hooks_riverpod: ^2.5.1
  langchain: ^0.7.2
  langchain_openai: ^0.6.2
  langchain_google: any
  langchain_pinecone: ^0.1.0+5
  pinecone: ^0.7.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  syncfusion_flutter_pdf: ^26.1.38
  path_provider: ^2.1.3
  langchain_core: ^0.3.2
  langchain_community: ^0.2.1+1
  camera: ^0.11.0+1
  path: any
  firebase_ml_model_downloader: ^0.3.0+1
  google_mlkit_image_labeling: ^0.12.0
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  provider: ^6.1.2
  firebase_core: ^3.1.1
  random_string: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  build_test: ^2.2.2
  riverpod_generator: any
  riverpod_lint: any
  custom_lint : any
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/pdf/
    - .env
    - assets/ml/

